language: node_js

node_js:
  - "node"

matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    sudo: required
install:
# Install required packages
  - sudo apt-get install -y inkscape
  - sudo -H pip install rst2html5
  - sudo -H pip install rst2pdf
  - sudo -H pip install svglib
# Install fonts
  - wget https://github.com/google/fonts/raw/master/ofl/ptmono/PTM55FT.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptsans/PT_Sans-Web-Bold.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptsans/PT_Sans-Web-BoldItalic.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptsans/PT_Sans-Web-Italic.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptsans/PT_Sans-Web-Regular.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptsansnarrow/PT_Sans-Narrow-Web-Bold.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptsansnarrow/PT_Sans-Narrow-Web-Regular.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptserif/PT_Serif-Web-Bold.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptserif/PT_Serif-Web-BoldItalic.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptserif/PT_Serif-Web-Italic.ttf -P /usr/share/fonts/
  - wget https://github.com/google/fonts/raw/master/ofl/ptserif/PT_Serif-Web-Regular.ttf -P /usr/share/fonts/
  - fc-cache -f -v

script:
  - git checkout $TRAVIS_BRANCH
  - ls
  - ls /usr/share/fonts
  - make html
  - make pdf
  - ls
  - ls pdf
  - git diff
  - git status
# Push back if changes detected
  - |
    echo Check for git changes...
    echo ${TRAVIS_COMMIT_MESSAGE}
    echo ${TRAVIS_REPO_SLUG}
    if git diff-index --no-ext-diff --name-only --exit-code HEAD ./camadapter ./index.html ./css ./head; then
        echo No changes detected
    else
        echo Detected changes
        echo This commit message is
        echo ${TRAVIS_COMMIT_MESSAGE}
        if [[ ${TRAVIS_COMMIT_MESSAGE} != *"norepush"* ]]; then
          echo Pushing changes back...
          git config --global user.email "travis@travis-ci.org"
          git config --global user.name "Travis CI"
          git commit -a -m "Travis automatic commit (__norepush__)"
          git remote add origin-pages https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG} > /dev/null 2>&1
          git push --quiet origin-pages master
          echo Pushing finished
        else
          echo Looks like it was a travis automatic commit. Don\'t push back.
        fi
    fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: pdf/*
  skip_cleanup: true
  on:
    tags: true

